<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'6LSo6YeP55uR566h');
$cfg_Cs[2]=array(1,1,1,'5Yi26Z2p55uR566h');
$cfg_Cs[3]=array(1,1,1,'5Yi26KGj55uR566h');
$cfg_Cs[4]=array(0,2,1,'5Lqn5ZOB5Lit5b+D');
$cfg_Cs[5]=array(4,2,1,'55qu6Z2p5bGV56S6');
$cfg_Cs[6]=array(4,2,1,'5oiQ6KGj5bGV56S6');
$cfg_Cs[7]=array(0,1,1,'546v5aKD5L+d5oqk');
$cfg_Cs[8]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[9]=array(8,1,1,'5YWs5Y+45LuL57uN');
$cfg_Cs[10]=array(8,1,1,'57uE57uH5p625p6E');
$cfg_Cs[11]=array(8,1,1,'6I2j6KqJ6LWE6LSo');
$cfg_Cs[12]=array(8,1,1,'6ZSA5ZSu572R57uc');
$cfg_Cs[13]=array(0,1,1,'6IGU57O75oiR5Lus');
?>