<li style="position: absolute; width: 418px; left: 0px; top: 0px;"> <a href="[field:imgsrc/]" class="jqzoom" rel="gal1" title="" style="outline-style: none; text-decoration: none;">
              <div class="zoomPad"><img width="418" height="600" src="[field:imgsrc/]" title="" style="opacity: 1;">
                <div class="zoomPup" style="top: 351.5px; left: 332px; width: 85px; height: 85px; position: absolute; border-width: 1px; display: none;"></div>
                <div class="zoomWindow" style="position: absolute; z-index: 5001; left: 422px; top: 100px; display: none;">
                  <div class="zoomWrapper" style="width: 290px;">
                    <div class="zoomWrapperTitle" style="width: 100%; position: absolute; display: none;"></div>
                    <div class="zoomWrapperImage" style="width: 100%; height: 290px;"><img src="[field:imgsrc/]" style="position: absolute; border: 0px; display: block; left: -1131.24401913876px; top: -1190.8625px;"></div>
                  </div>
                </div>
                <div class="zoomPreload" style="visibility: hidden; top: 278.5px; left: 164px; position: absolute;">Loading zoom</div>
              </div>
              </a></li>